##
## Makefile for UI in /home/pierre/rendu/TEK2/PSU_2016_zappy/gui
## 
## Made by PierreBougon
## Login   <pierre@epitech.net>
## 
## Started on  Sat Jun 10 22:03:36 2017 PierreBougon
## Last update Sat Jun 10 22:28:30 2017 PierreBougon
##

include ../mk/colors.mk ../mk/commands.mk ../mk/definitions.mk


#############################
#####   GUI variables   #####
#############################

PROJECT_NAME=		zappy_gui

NAME=			../$(PROJECT_NAME)


# Project sources

MAIN_SRC=		main.c

SRC=			$(addprefix src/, $(MAIN_SRC))

OBJ=			$(SRC:.c=.o)

INC=			-Iinclude

LDFLAGS+=

CFLAGS+=

## Core rules

include ../mk/rules.mk
