##
## Makefile for AI in /home/pierre/rendu/TEK2/PSU_2016_zappy
## 
## Made by PierreBougon
## Login   <pierre@epitech.net>
## 
## Started on  Sat Jun 10 21:41:56 2017 PierreBougon
## Last update Sat Jun 10 22:02:58 2017 PierreBougon
##

include ../mk/colors.mk ../mk/commands.mk ../mk/definitions.mk


#############################
#####   AI variables    #####
#############################

PROJECT_NAME=		zappy_ai

NAME=			../$(PROJECT_NAME)


# Project sources

MAIN_SRC=		main.c

SRC=			$(addprefix src/, $(MAIN_SRC))

OBJ=			$(SRC:.c=.o)

INC=			-Iinclude

LDFLAGS+=

CFLAGS+=

## Core rules

include ../mk/rules.mk
